version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      cache_from:
        - boostflow:latest
        - boostflow:deps
        - boostflow:builder
    image: boostflow:latest
    container_name: boostflow-nextjs
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge