services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boostflow-nextjs
    restart: always
    env_file:
      - .env.local
    ports:
      - "3000:3000"

    volumes:
      - ./uploads:/app/uploads
    networks:
      - nextjs-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailhog:
    image: mailhog/mailhog:latest
    container_name: boostflow-mailhog
    restart: always
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge